### ISSUE TITLE
Could not initialize class com.johnlindquist.acejump.view.Model

### ISSUE THREAD

**Issue by Huang-Jinxian** [acejump/AceJump#130]
Could not initialize class com.johnlindquist.acejump.ui.AceUI
java.lang.NoClassDefFoundError: Could not initialize class com.johnlindquist.acejump.ui.AceUI
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.e(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by holgerbrandl** [comment]
Same with me using:
> IntelliJ IDEA 2016.3.5
> Build #IU-163.13906.18, built on March 6, 2017

and AceJump v3.2.0

**Comment by breandan** [comment]
Can you reproduce this issue, or does it happen sporadically? Please report if updating to the latest version (3.2.3+) does not help. Thanks.

**Comment by breandan** [comment]
Possibly related: #127

**Comment by breandan** [comment]
I think [this line](https://github.com/johnlindquist/AceJump/blob/master/src/main/kotlin/com/johnlindquist/acejump/ui/AceUI.kt#L45) may be the culprit:

```
var naturalColor = getInstance().globalScheme.getColor(CARET_COLOR)!!
```

**Comment by ooopscc** [comment]
@breandan It doesn't seem to be working by adding default color in c9d3bf3. I build from source(including that commit) and restart AppCode to make it load, still got that error message. 
But when I set caret foreground color in editor setting, it works.

**Comment by aristotll** [comment]
Similar bug when using AceJump with idea vim `com.johnlindquist.acejump.view.Model` cannot be found( I use the latest stable version of idea
```
Could not initialize class com.johnlindquist.acejump.view.Model
java.lang.NoClassDefFoundError: Could not initialize class com.johnlindquist.acejump.view.Model
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:24)
	at com.maddyhome.idea.vim.KeyHandler.executeAction(KeyHandler.java:631)
	at com.maddyhome.idea.vim.ex.handler.ActionHandler.executeAction(ActionHandler.java:68)
	at com.maddyhome.idea.vim.ex.handler.ActionHandler.access$000(ActionHandler.java:38)
	at com.maddyhome.idea.vim.ex.handler.ActionHandler$1.run(ActionHandler.java:59)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by breandan** [comment]
Made a bunch of changes which should fix this issue. Stack traces are no longer relevant, closing.
