### ISSUE TITLE
Editor is already disposed

### ISSUE THREAD

**Issue by breandan** [acejump/AceJump#175]
```
Editor is already disposed
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor is already disposed
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:94)
	at com.intellij.openapi.editor.impl.EditorImpl.throwDisposalError(EditorImpl.java:836)
	at com.intellij.openapi.editor.impl.view.TextLayoutCache.c(TextLayoutCache.java:199)
	at com.intellij.openapi.editor.impl.view.TextLayoutCache.getLineLayout(TextLayoutCache.java:158)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.d(VisualLineFragmentsIterator.java:171)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.a(VisualLineFragmentsIterator.java:161)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.a(VisualLineFragmentsIterator.java:143)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.<init>(VisualLineFragmentsIterator.java:95)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.lambda$create$0(VisualLineFragmentsIterator.java:41)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.visualToLogicalPosition(EditorCoordinateMapper.java:142)
	at com.intellij.openapi.editor.impl.view.EditorView.visualToLogicalPosition(EditorView.java:179)
	at com.intellij.openapi.editor.impl.EditorImpl.visualToLogicalPosition(EditorImpl.java:1993)
	at com.johnlindquist.acejump.search.AceUtilKt.visualLineToLogicalLine(AceUtil.kt:161)
	at com.johnlindquist.acejump.search.AceUtilKt.getView(AceUtil.kt:70)
	at com.johnlindquist.acejump.control.Handler.restoreScroll(Handler.kt:233)
	at com.johnlindquist.acejump.control.Handler.restoreSettings(Handler.kt:227)
	at com.johnlindquist.acejump.control.Handler.reset(Handler.kt:196)
	at com.johnlindquist.acejump.view.Model.setEditor(Model.kt:31)
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:16)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:621)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jcraane** [comment]
I also have this error in Android Studio 2.3.3

**Comment by toolchainX** [comment]
I also have this error in gogland 1.0 preview

**Comment by saroff** [comment]
This error happened to me on 
WebStorm 2017.2.3 EAP
Build #WS-172.3968.20, built on August 23, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0


Looks like it can be connected to https://github.com/johnlindquist/AceJump/issues/185
I had linked issue before (on WebStorm 2017.2.2), but now this error occured instead.
I think this is the same problem, it can be reproduced as stated in linked issue - create a lot of split windows then close some of them, but now this error appears.

**Comment by breandan** [comment]
Thanks, will investigate. Possibly related to #178 as well.

**Comment by breandan** [comment]
I think this issue should be fixed but please feel free to reopen if you should encounter it again on a recent version.
