### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by zeghaun** [acejump/AceJump#246]
idea16.3  jdk1.8  acejump3.5.0   thanks 

kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
	at com.johnlindquist.acejump.view.Canvas$storeBounds$1.<init>(Canvas.kt)
	at com.johnlindquist.acejump.view.Canvas.storeBounds(Canvas.kt:47)
	at com.johnlindquist.acejump.view.Canvas.bindCanvas(Canvas.kt:35)
	at com.johnlindquist.acejump.control.Handler.configureEditor(Handler.kt:75)
	at com.johnlindquist.acejump.control.Handler.start(Handler.kt:107)
	at com.johnlindquist.acejump.control.Handler.access$start(Handler.kt:32)
	at com.johnlindquist.acejump.control.Handler$activate$1.invoke(Handler.kt:52)
	at com.johnlindquist.acejump.control.Handler$activate$1.invoke(Handler.kt:32)
	at com.johnlindquist.acejump.search.AceUtilKt$sam$Runnable$b83511ca.run(AceUtil.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:647)
	at com.johnlindquist.acejump.search.AceUtilKt.runAndWait(AceUtil.kt:37)
	at com.johnlindquist.acejump.control.Handler.activate(Handler.kt:52)
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by zeghaun** [comment]
kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V

**Comment by breandan** [comment]
Oh no! Another occurrence of #200. I think it has something to do with the bundled JDK, older platform versions do not support the [`::` syntax](https://github.com/acejump/AceJump/blob/6ca3ec3d6bec852c4dc026031fa820e785481c8f/src/main/kotlin/org/acejump/view/Canvas.kt#L47). Thank you for reporting!
