### ISSUE TITLE
Access is allowed from event dispatch thread only.

### ISSUE THREAD

**Issue by jornetsimon** [acejump/AceJump#253]
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@4e69c863
Current thread: Thread[ApplicationImpl pooled thread 36,4,Idea Thread Group] 1438827452
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1147678151
	at com.intellij.openapi.application.impl.ApplicationImpl.b(ApplicationImpl.java:1123)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1112)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:151)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.registerInTree(RangeHighlighterImpl.java:363)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:73)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:115)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:166)
	at org.acejump.search.Finder.createTextHighlight(Finder.kt:127)
	at org.acejump.search.Finder.paintTextHighlights(Finder.kt:115)
	at org.acejump.search.Finder.paintTextHighlights$default(Finder.kt:111)
	at org.acejump.search.JumpMode$Companion.setMode(JumpMode.kt:26)
	at org.acejump.search.JumpMode$Companion.reset(JumpMode.kt:47)
	at org.acejump.search.Jumper.reset(Jumper.kt:102)
	at org.acejump.control.Handler$clear$1.invoke(Handler.kt:68)
	at org.acejump.control.Handler$clear$1.invoke(Handler.kt:36)
	at org.acejump.search.AceUtilKt.applyTo(AceUtil.kt:25)
	at org.acejump.control.Handler.clear(Handler.kt:68)
	at org.acejump.control.Handler.reset(Handler.kt:160)
	at org.acejump.control.Handler.repaintTagMarkers(Handler.kt:130)
	at org.acejump.search.Finder.tag(Finder.kt:138)
	at org.acejump.search.Finder.access$tag(Finder.kt:29)
	at org.acejump.search.Finder$search$$inlined$runAsync$1.run(promise.kt:290)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Happened when triggering the shortcut then using right arrow.

**Comment by breandan** [comment]
Thank you for reporting. Duplicates #251, please follow that thread for updates.
