### ISSUE TITLE
java.util.NoSuchElementException: List is empty (PyCharm)

### ISSUE THREAD

**Issue by hriundel** [acejump/AceJump#265]
When I activate AceJump with Ctrl-; and press any character, it throws NoSuchElementException (traceback below). I can still navigate around so plugin seems to be functioning properly afaik, but the IDE keeps flashing red at me and complaining that internal error has occurred.

Let me know if you need any more info. Thanks!

### Environment: 
AceJump 3.5.3
PyCharm 2018.3.1 (Professional Edition)
Build #PY-183.4588.64, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2 (Mojave)

### Traceback (truncated)
```
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:197)
	at org.acejump.label.Tagger.nextOrNearestVisibleOffset(Tagger.kt:122)
	at org.acejump.view.Marker.highlightEditorText(Marker.kt:115)
	at org.acejump.view.Marker.paint(Marker.kt:94)
	at com.intellij.openapi.editor.impl.view.EditorPainter.lambda$paintCustomRenderers$1(EditorPainter.java:377)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.processRangeHighlightersOverlappingWith(MarkupModelImpl.java:247)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paintCustomRenderers(EditorPainter.java:374)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:94)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:264)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1849)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:233)
	at javax.swing.JComponent.paint(JComponent.java:1057)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:119)
	at javax.swing.JComponent.paintChildren(JComponent.java:890)
	at javax.swing.JComponent.paint(JComponent.java:1066)
	at javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:234)
        ...
```

**Comment by breandan** [comment]
Thank you for reporting. This issue should be fixed in `3.5.4`, please reopen if this is not the case.
