### ISSUE TITLE
Editor is already disposed if tab placement == none

### ISSUE THREAD

**Issue by jmdesprez** [acejump/AceJump#297]
AceJump 3.5.7
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Maybe related to #187 and/or #175 

Steps to reproduce:

- Start IntelliJ.
- Configure it to not use tab (Editor > General > Editor Tabs > Tab placement : None
- Activate AceJump twice to enter into the "Declaration mode"
- Type something to search
- Validate

Expected : cursor moved to requested position and "Navigate > Declaration or Usages" is invoked. For example, if you focus a method call, you should go to the method itself.

Outcome: the current editor is closed and the plugin crash.

Workaround : configure IntelliJ to use Tabs :)

Also notice that the behavior is the same regardless of the value of the parameter "Editor > General > Editor Tabs > Tab placement > Open declaration source in the same tab"

----

stacktrace.txt (not the full one) : 
```
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor is already disposed
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:101)
	at com.intellij.openapi.editor.impl.EditorImpl.throwDisposalError(EditorImpl.java:1001)
	at com.intellij.openapi.editor.impl.view.TextLayoutCache.checkDisposed(TextLayoutCache.java:194)
	at com.intellij.openapi.editor.impl.view.TextLayoutCache.getLineLayout(TextLayoutCache.java:153)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.setFragmentIterator(VisualLineFragmentsIterator.java:171)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.setInlaysAndFragmentIterator(VisualLineFragmentsIterator.java:162)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.init(VisualLineFragmentsIterator.java:149)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.<init>(VisualLineFragmentsIterator.java:93)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.lambda$create$0(VisualLineFragmentsIterator.java:35)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.visualToLogicalPosition(EditorCoordinateMapper.java:189)
	at com.intellij.openapi.editor.impl.view.EditorView.visualToLogicalPosition(EditorView.java:179)
	at com.intellij.openapi.editor.impl.EditorImpl.visualToLogicalPosition(EditorImpl.java:2222)
	at org.acejump.search.AceUtilKt.visualLineToLogicalLine(AceUtil.kt:214)
	at org.acejump.search.AceUtilKt.getView(AceUtil.kt:112)
	at org.acejump.control.Scroller.restoreScroll(Scroller.kt:95)
	at org.acejump.control.Handler$restoreSettings$1.invoke(Handler.kt:124)
	at org.acejump.control.Handler$restoreSettings$1.invoke(Handler.kt:28)
	at org.acejump.search.AceUtilKt$sam$java_lang_Runnable$0.run(AceUtil.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:630)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:643)
	at org.acejump.search.AceUtilKt.runNow(AceUtil.kt:40)
	at org.acejump.control.Handler.restoreSettings(Handler.kt:120)
	at org.acejump.control.Handler.reset(Handler.kt:117)
	at org.acejump.control.Listener.ancestorRemoved(Listener.kt:80)
...
```
I don't provide "creation.trace" and "kill.trace" as I see no trace of the plugin in the stacktrace. 

Feel free to ask for more information :)

**Comment by jmdesprez** [comment]
_Disclaimer : I've no experience in building IntelliJ plugin ;)_

I've investigate on the problem, here what I've found so far.

In `org.acejump.control.Scroller#restoreScroll` the call to `getView()` is problematic if the editor is already disposed. I think this version is safer : 

```
  fun Editor.restoreScroll() {
    if (!isDisposed && caretModel.offset !in getView()) {
      scrollingModel.scrollVertically(scrollY)
      scrollingModel.scrollHorizontally(scrollX)
    }
  }
```

The method `org.acejump.control.Handler#restoreCaret` is also problematic (in a more sneaky way) because the method `com.intellij.openapi.editor.impl.SettingsImpl#setBlockCursor` crash if the editor is disposed.

So, maybe the solution should be a check at a higher level. Maybe changing `org.acejump.control.Handler#restoreSettings` like this : 

```
  private fun Editor.restoreSettings() = runNow {
    enabled = false
    swapActionHandler()
    uninstallKeyHandler()
    if(!isDisposed) {
      restoreScroll()
      restoreCanvas()
      restoreCaret()
      restoreColors()
    }
  }
```

I suppose that `swapActionHandler()` and `uninstallKeyHandler()` should always be called. At least both methods work if the editor is disposed.

My two cents ;)

**Comment by breandan** [comment]
Interesting, thank you for investigating this issue @jmdesprez! Would you be interested submitting a PR so we can give you credit for this fix?

**Comment by jmdesprez** [comment]
Sure :)

I will have a look at the contribution section then create a PR asap.
