### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by issacchow** [acejump/AceJump#336]
It worked correctly for many days but suddenly not worked. As I press hot keys to try to use ,idea show following error:

`java.lang.ExceptionInInitializerError
	at org.acejump.control.AceAction.actionPerformed(AceAction.kt:28)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassCastException: com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl cannot be cast to com.intellij.openapi.editor.Editor
	at org.acejump.search.AceUtilKt.defaultEditor(AceUtil.kt:284)
	at org.acejump.view.Model.<clinit>(Model.kt:23)
	... 18 more`

-  Idea Version:  2018.2.3 (Ultimate Edition)
-  OS: Mac OS X
- AceJump: 3.5.2

**Comment by breandan** [comment]
Thanks to #353, this should be fixed in `3.7.0`, but feel free to reopen if you re-encounter it.
