### ISSUE TITLE
pycharm and acejump3.7.1 error

### ISSUE THREAD

**Issue by BXBaskershu** [acejump/AceJump#367]
**Describe the bug**
After upgrading to 3.7.1, an error occurs when using the jump function, and the code cannot be modified unless restarted

**To Reproduce**
1. enter <lead><lead><b> 
2. enter character jump to target
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/49138329/115982591-08d62f80-a5cf-11eb-9d10-60080386c823.png)
```
java.lang.AbstractMethodError: Receiver class org.jetbrains.plugins.extension.easymotion.StandardHandler$execute$1 does not define or inherit an implementation of the resolved method 'abstract void finished(java.lang.String, java.lang.String)' of interface org.acejump.session.AceJumpListener.
	at org.acejump.session.Session.dispose$acejump(Session.kt:252)
	at org.acejump.session.SessionManager.end(SessionManager.kt:40)
	at org.acejump.session.Session.end(Session.kt:226)
	at org.acejump.session.Session.updateSearch(Session.kt:128)
	at org.acejump.session.Session.access$updateSearch(Session.kt:32)
	at org.acejump.session.Session$1.execute(Session.kt:92)
	at org.acejump.input.EditorKeyListener.execute(EditorKeyListener.kt:19)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$2(TypedAction.java:185)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$3(TypedAction.java:184)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:184)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1299)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1281)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3400)
	at com.intellij.openapi.editor.impl.EditorImpl$7.keyTyped(EditorImpl.java:1120)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6607)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2852)
	at java.desktop/java.awt.Component.processEvent(Component.java:6429)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:879)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1162)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1018)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4908)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:893)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Desktop (please complete the following information):**
 - OS: macos 15.6
 - pycharm 2021.1.1
 - AceJump 3.7.1

**Comment by breandan** [comment]
This is an issue for [IdeaVim-EasyMotion](https://github.com/AlexPl292/IdeaVim-EasyMotion). It can be fixed by downgrading AceJump to `3.7.0` manually or disabling IdeaVim-EasyMotion. cc: @AlexPl292 Sorry! I think #357 broke the integration again :(

**Comment by AlexPl292** [comment]
Hi there! The update of IdeaVim-EasyMotion is here, please update to 1.6 version 🚀 

@breandan Yeah, compatibility between plugins is complicated :( Actually, I have a job with a daily task that checks IdeaVim-EasyMotion against masters of IdeaVim and AceJump. I believe this can notify us when we get compatibility issues: https://teamcity.jetbrains.com/buildConfiguration/IdeaVim_IdeaVimEasyMotion_BuildMaster#3440231

**Comment by breandan** [comment]
Will keep an eye on that. It seems to me like it should be possible for the platform to detect these kinds of API incompatibilities through static analysis on the plugin (similar to the way the [intellij-plugin-verifier](https://github.com/JetBrains/intellij-plugin-verifier) works) and warn the user that a plugin may be incompatible before auto-updating. 

@serejke What happened here was that [an API signature changed](https://github.com/acejump/AceJump/commit/4622fbb20b4a84dcceb16fa0c19c3f54b60396c9#diff-637839c18b6814d3b98eefb65c92f6d7f8960b249a117e87699dc568f3bcdb4fL27), and a third-party plugin which [depends on this plugin](https://github.com/AlexPl292/IdeaVim-EasyMotion/blob/f35d68f907d8a120ca54f475ab98c0c3b97919db/build.gradle#L28) was broken when this plugin was auto-updated by the IDE. Perhaps it is possible to detect updates containing incompatible API signatures prior to loading it.
