### ISSUE TITLE
acejump 3.8 report error when edit  java file

### ISSUE THREAD

**Issue by MaxSherry** [acejump/AceJump#372]
idea 2021.1.1
when i edit java file more time , report error and acejump can't work  

```
java.lang.IndexOutOfBoundsException: Illegal start index
	at java.base/java.util.regex.Matcher.find(Matcher.java:771)
	at kotlin.text.RegexKt.findNext(Regex.kt:266)
	at kotlin.text.RegexKt.access$findNext(Regex.kt:1)
	at kotlin.text.Regex.find(Regex.kt:120)
	at org.acejump.search.SearchProcessor.<init>(SearchProcessor.kt:35)
	at org.acejump.search.SearchProcessor.<init>(SearchProcessor.kt)
	at org.acejump.search.SearchProcessor$Companion.fromRegex(SearchProcessor.kt:24)
	at org.acejump.session.Session.startRegexSearch(Session.kt:185)
	at org.acejump.session.Session.startRegexSearch(Session.kt:199)
	at org.jetbrains.plugins.extension.easymotion.EasyMotionExtension$PredefinedPattern.customization(EasyMotionExtension.kt:378)
	at org.jetbrains.plugins.extension.easymotion.EasyHandlerBase.rightAfterAction(Processors.kt:110)
	at org.jetbrains.plugins.extension.easymotion.StandardHandler.execute(Processors.kt:64)
	at com.maddyhome.idea.vim.key.ToHandlerMappingInfo$execute$1.run(MappingInfo.kt:133)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.maddyhome.idea.vim.key.ToHandlerMappingInfo.execute(MappingInfo.kt:132)
	at com.maddyhome.idea.vim.KeyHandler.handleCompleteMappingSequence(KeyHandler.java:452)
	at com.maddyhome.idea.vim.KeyHandler.handleKeyMapping(KeyHandler.java:367)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:226)
	at com.maddyhome.idea.vim.key.ToKeysMappingInfo.execute(MappingInfo.kt:99)
	at com.maddyhome.idea.vim.KeyHandler.handleCompleteMappingSequence(KeyHandler.java:452)
	at com.maddyhome.idea.vim.KeyHandler.handleKeyMapping(KeyHandler.java:367)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:226)
	at com.maddyhome.idea.vim.KeyHandler.handleCompleteMappingSequence(KeyHandler.java:456)
	at com.maddyhome.idea.vim.KeyHandler.handleKeyMapping(KeyHandler.java:367)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:226)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:166)
	at com.maddyhome.idea.vim.VimTypedActionHandler.execute(VimTypedActionHandler.kt:67)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$2(TypedAction.java:185)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$3(TypedAction.java:184)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:184)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1299)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1281)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3400)
	at com.intellij.openapi.editor.impl.EditorImpl$7.keyTyped(EditorImpl.java:1120)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6607)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2852)
	at java.desktop/java.awt.Component.processEvent(Component.java:6429)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:879)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1158)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1018)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4908)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:893)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by breandan** [comment]
This should be fixed in [`3.8.1`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/119664). Please give it a try and report back if you encounter any other issues.
