### ISSUE TITLE
RubyMine: IDE Fatal Errors on launch

### ISSUE THREAD

**Issue by ooopscc** [acejump/AceJump#400]
**Describe the bug**
IDE Fatal Errors window shows when launch.

**To Reproduce**
_for me just launch_

**Expected behavior**
not error window shows

**Screenshots**
<img width="587" alt="image" src="https://user-images.githubusercontent.com/1056803/159954633-8ad9c3c0-41c1-43d8-bf8d-75be5effc435.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.3
 - IDE and version: RubyMine 2021.3.3
 - AceJump version: 3.8.6

**Additional context**
<details>
  <summary>stacktrace.txt</summary>
<pre>
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type Ruby:Brace code block (class org.jetbrains.plugins.ruby.ruby.lang.psi.stubs.types.RCodeBlockStubElementType)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:80)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:239)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.RPsiElementBaseImpl.getLanguageLevel(RPsiElementBaseImpl.java:104)
	at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.RStubBasedPsiElementBase.getLanguageLevel(RStubBasedPsiElementBase.java:69)
	at org.jetbrains.plugins.ruby.ruby.actions.intention.bracestodo.BraceConverter.replaceBlock(BraceConverter.java:51)
	at org.jetbrains.plugins.ruby.ruby.actions.editor.handlers.RubyEnterHandler.handleEnterInBraceBlock(RubyEnterHandler.java:396)
	at org.jetbrains.plugins.ruby.ruby.actions.editor.handlers.RubyEnterHandler.preprocessEnter(RubyEnterHandler.java:235)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteActionInner(EnterHandler.java:119)
	at com.intellij.codeInsight.editorActions.EnterHandler.lambda$executeWriteAction$0(EnterHandler.java:64)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.lambda$disablePostprocessFormattingInside$2(PostprocessReformattingAspect.java:120)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:128)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:63)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:66)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:202)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:66)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$2(EditorActionHandler.java:192)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$3(EditorActionHandler.java:191)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:312)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:421)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:321)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:296)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:189)
	at org.acejump.action.AceEditorAction.doExecute(AceEditorAction.kt:24)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerSmartStepIntoHandler$SmartStepEditorActionHandler.doExecute(XDebuggerSmartStepIntoHandler.java:417)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:63)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.maddyhome.idea.vim.helper.ActionExecutor.executeAction(ActionExecutor.java:70)
	at com.maddyhome.idea.vim.group.ChangeGroup.processEnter(ChangeGroup.java:606)
	at com.maddyhome.idea.vim.action.change.insert.InsertEnterAction.execute(InsertEnterAction.kt:38)
	at com.maddyhome.idea.vim.handler.VimActionHandler.baseExecute(VimActionHandler.kt:73)
	at com.maddyhome.idea.vim.handler.EditorActionHandlerBase.doExecute(EditorActionHandlerBase.kt:102)
	at com.maddyhome.idea.vim.handler.EditorActionHandlerBase.access$doExecute(EditorActionHandlerBase.kt:57)
	at com.maddyhome.idea.vim.handler.EditorActionHandlerBase$execute$action$1.invoke(EditorActionHandlerBase.kt:83)
	at com.maddyhome.idea.vim.handler.EditorActionHandlerBase$execute$action$1.invoke(EditorActionHandlerBase.kt:83)
	at com.maddyhome.idea.vim.handler.EditorActionHandlerBase.execute(EditorActionHandlerBase.kt:87)
	at com.maddyhome.idea.vim.helper.VimActionExecutor.lambda$executeVimAction$0(VimActionExecutor.java:47)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.maddyhome.idea.vim.helper.VimActionExecutor.executeVimAction(VimActionExecutor.java:47)
	at com.maddyhome.idea.vim.KeyHandler$ActionRunner.run(KeyHandler.kt:898)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.maddyhome.idea.vim.helper.RunnableHelper.runWriteCommand$lambda-3(RunnableHelper.kt:43)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.maddyhome.idea.vim.helper.RunnableHelper.runWriteCommand(RunnableHelper.kt:43)
	at com.maddyhome.idea.vim.KeyHandler.executeCommand(KeyHandler.kt:716)
	at com.maddyhome.idea.vim.KeyHandler.finishedCommandPreparation(KeyHandler.kt:245)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:231)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.kt:125)
	at com.maddyhome.idea.vim.action.VimShortcutKeyAction.actionPerformed(VimShortcutKeyAction.kt:83)
	at com.intellij.openapi.actionSystem.EmptyAction$MyDelegatingAction.actionPerformed(EmptyAction.java:103)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:573)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:260)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:702)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:456)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:224)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</pre>
</details>
<details>
  <summary>invalidation.trace</summary>
<pre>
</pre>
</details>

**Plugins**
```
AceJump (3.8.6)
GitHub Copilot (1.1.14.882)
IdeaVim (1.10.0)
Material Theme UI (6.15.0)
```

**Comment by chylex** [comment]
`org.acejump.action.AceEditorAction` is part of a chain of action handlers, in this case the action was not related to AceJump so it simply delegated to the default IntelliJ handler and eventually crashed inside the built-in Ruby plugin.

If you can provide reproduction steps and can confirm that this issue only happens when AceJump is enabled, please reopen the issue with more details.
