### ISSUE TITLE
Not usable in Android Studio Giraffe: `NoSuchFieldError: Companion` in `AceAction.actionPerformed`

### ISSUE THREAD

**Issue by h0tk3y** [acejump/AceJump#434]
An attempt to use AceJump in Android Studio Giraffe 2022.3.1 Beta 3 fails with an exception.

**To Reproduce**
1. Run Android Studio Giraffe with AceJump installed
2. Trigger the `Activate / Cycle AceJump Mode` action
3. The exception is thrown with the following stack trace:
    ```stacktrace
    java.lang.NoSuchFieldError: Companion
		at org.acejump.action.AceAction.actionPerformed(AceAction.kt:35)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)
		at com.intellij.ide.actions.GotoActionAction.lambda$performActionImpl$4(GotoActionAction.java:91)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
		at com.intellij.ide.actions.GotoActionAction.performActionImpl(GotoActionAction.java:90)
		at com.intellij.ide.actions.GotoActionAction.lambda$performAction$2(GotoActionAction.java:70)
		at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
		at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
		at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
		at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
		at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
		at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
		at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
		at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
		at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
		at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
		at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
		at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
    ```

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4
 - IDE and version: Android Studio Giraffe 2022.3.1 Beta 3 Android Studio Giraffe Build #AI-223.8836.35.2231.10075884
 - AceJump version 3.8.13

**Comment by breandan** [comment]
Related to #432, #435. Can you try updating to [Android Studio 2023.1.1 Canary 4](https://developer.android.com/studio/preview) and reporting back? Thanks.

**Comment by h0tk3y** [comment]
It works fine for me in 2023.1.1 Canary 4. Thank you, and sorry for bothering, then.

**Comment by laurensvanpoucke** [comment]
got the same issue in WebStorm (Build #WS-223.8617.44)

**Comment by breandan** [comment]
@laurensvanpoucke I think you're still on the `2022.3` release. Could you try updating WebStorm to `2023.1+` and reporting back?
